spring:
  application:
    name: simple-transaction
  config:
    import: configtree:${SECRET_PATH}
  datasource:
    url: ${DATASOURCE_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: stserver
    password: ${secret_mysql_app_password}
  kafka:
    consumer:
      group-id: st-server-group
      auto-offset-reset: latest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.trusted.packages: com.ywcheong.simple.transaction.account.domain
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    bootstrap-servers: ${BROKER_URL}

st:
  secret:
    jwt-pubkey: ${secret_server_jwt_pubkey}
    jwt-prvkey: ${secret_server_jwt_prvkey}
  kafka-topic: st-events

springdoc:
  api-docs:
    path: /help/docs
  swagger-ui:
    path: /help/ui