networks:
  st-bridge:
    driver: bridge

services:
  st-dbms:
    image: mysql:8.0
    container_name: st-dbms-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: stdb
      MYSQL_USER: stserver
      MYSQL_PASSWORD_FILE: /run/secrets/secret_mysql_app_password
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/secret_mysql_root_password
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d:ro
    secrets:
      - secret_mysql_root_password
      - secret_mysql_app_password
    ports:
      - "3306:3306"
    networks:
      - st-bridge

  st-obs:
    image: grafana/otel-lgtm:latest
    container_name: st-obs-otel-lgtm
    volumes:
      - grafana_data:/data/grafana
      - prometheus_data:/data/prometheus
      - ./prometheus-init/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - loki_data:/data/loki
    env_file:
      - ../env/obs.base.env
    ports:
      - "4317:4317" # OpenTelemetry gRPC
      - "4318:4318" # OpenTelemetry HTTP
      - "3000:3000" # Web dashboard
    networks:
      - st-bridge

  st-init:
    image: alpine
    container_name: st-infra-init
    entrypoint: [ "ls" ] # Nothing to do right now
    depends_on:
      - st-dbms
      - st-obs
    networks:
      - st-bridge

volumes:
  mysql_data:
    driver: local
  grafana_data:
    driver: local
  prometheus_data:
    driver: local
  loki_data:
    driver: local

secrets:
  secret_mysql_root_password:
    file: ../secret/secret_mysql_root_password
  secret_mysql_app_password:
    file: ../secret/secret_mysql_app_password
  secret_server_jwt_pubkey:
    file: ../secret/secret_server_jwt_pubkey
  secret_server_jwt_prvkey:
    file: ../secret/secret_server_jwt_prvkey